FROM node:8.11.2-alpine as build
RUN set -x \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
    udev \
    ttf-freefont \
    bash \
    python \
    make \
    g++ \
    vim
WORKDIR /webapp
COPY ./package.json .
RUN npm install
COPY . .
